# Generated by Django 4.2 on 2024-07-01 04:28

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_form_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField(max_length=64)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('numero_romano', models.CharField(max_length=10)),
                ('numero_region', models.SmallIntegerField()),
                ('abreviacion', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='TipoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(choices=[('Parcela', 'Parcela'), ('Casa', 'Casa'), ('Departamento', 'Departamento')])),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(choices=[('Arrendador', 'Arrendador'), ('Arrendatario', 'Arrendatario')])),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segundo_nombre', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('rut', models.IntegerField(blank=True, null=True)),
                ('dv', models.SmallIntegerField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('telefono', models.BigIntegerField(blank=True, null=True)),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='app.comuna')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='app.region')),
                ('tipo_usuario', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='app.tipousuario')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('metros_cuadrados_terreno', models.IntegerField()),
                ('metros_cuadrados_construidos', models.IntegerField(default=0)),
                ('cantidad_estacionamientos', models.SmallIntegerField(default=0)),
                ('cantidad_habitaciones', models.SmallIntegerField(default=0)),
                ('cantidad_banios', models.SmallIntegerField(default=0)),
                ('precio_mensual', models.FloatField(default=0)),
                ('direccion', models.CharField(max_length=100)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmueble', to='app.comuna')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmueble', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmueble', to='app.region')),
                ('tipo_inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmueble', to='app.tipoinmueble')),
            ],
        ),
        migrations.CreateModel(
            name='ContactArrendatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visto', models.BooleanField(default=False)),
                ('oferta', models.IntegerField()),
                ('mensaje', models.TextField(max_length=2000)),
                ('creacion_registro', models.DateField(auto_now_add=True)),
                ('id_arrendador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactoArrendador', to=settings.AUTH_USER_MODEL)),
                ('id_arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactoArrendatario', to=settings.AUTH_USER_MODEL)),
                ('id_inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactoArrendatario', to='app.inmueble')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comuna', to='app.region'),
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_id', models.IntegerField()),
                ('imagen', cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipoImagen', to='app.tipoimagen')),
                ('id_inmueble', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles', to='app.inmueble')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('categoria', 'id')},
            },
        ),
    ]
