# Generated by Django 4.2 on 2024-05-31 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comuna',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='app.comuna'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='app.region'),
            preserve_default=False,
        ),
    ]
