# Generated by Django 4.2 on 2024-07-01 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_imagenes_id_inmueble'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='id_inmueble',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles', to='app.inmueble'),
        ),
    ]
