# Generated by Django 4.2 on 2024-06-01 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_alter_profile_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='primer_apellido',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='primer_nombre',
        ),
        migrations.AlterField(
            model_name='comuna',
            name='region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comuna', to='app.region'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='cantidad_banios',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='cantidad_estacionamientos',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='cantidad_habitaciones',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmueble', to='app.comuna'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='metros_cuadrados_construidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='precio_mensual',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmueble', to='app.region'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='tipo_inmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmueble', to='app.tipoinmueble'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='app.comuna'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='direccion',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='app.region'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='segundo_apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='segundo_nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tipo_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='app.tipousuario'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
