# Generated by Django 4.2 on 2024-06-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_contactform_alter_profile_dv_alter_profile_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telefono',
            field=models.BigIntegerField(default=1),
        ),
    ]
