# Generated by Django 4.2 on 2024-06-07 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_alter_profile_comuna_alter_profile_dv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='id_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inmueble', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
