# Generated by Django 4.2 on 2024-06-08 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_inmueble_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dv',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rut',
            field=models.IntegerField(),
        ),
    ]
