# Generated by Django 4.2 on 2024-06-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_profile_dv_alter_profile_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dv',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rut',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefono',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
