# Generated by Django 4.2 on 2024-06-09 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_profile_comuna_alter_profile_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='app.comuna'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='app.region'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tipo_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='app.tipousuario'),
        ),
    ]
