# Generated by Django 4.2 on 2024-06-09 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0015_alter_profile_comuna_alter_profile_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactArrendatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visto', models.BooleanField(default=False)),
                ('oferta', models.IntegerField()),
                ('mensaje', models.TextField(max_length=2000)),
                ('id_arrendador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactoArrendador', to=settings.AUTH_USER_MODEL)),
                ('id_arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactoArrendatario', to=settings.AUTH_USER_MODEL)),
                ('id_inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactoArrendatario', to='app.inmueble')),
            ],
        ),
    ]
