# Generated by Django 4.2 on 2024-06-10 01:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_contactarrendatario'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactarrendatario',
            name='creacion_registro',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
